services:
  kafka:
    image: apache/kafka:latest
    ports:
      - 9092:9092
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - app-network

  notificationservice:
    build:
      context: ./notificationservice
    ports:
      - 5000:5000
    volumes:
      - ./notificationservice:/app
    depends_on:
      - kafka
    networks:
      - app-network

  emailsender:
    build:
      context: ./emailsender
    ports:
      - 5001:5001
    volumes:
      - ./emailsender:/app
    depends_on:
      - kafka
    networks:
      - app-network

  smssender:
    build:
      context: ./smssender
    ports:
      - 5002:5002
    volumes:
      - ./smssender:/app
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
